export default {
	
	AUTH_LOGIN: 1,
	AUTH_LOGOUT: 2,
	USER_DATA_LOAD: 3,
	USER_DATA_SAVE: 4,
	SELECT_PAGE: 5,
	USER_DATA_SET: 6,
	USER_DATA_ADD_OPTIONAL_PHOTO: 7,
	USER_DATA_DELETE_OPTIONAL_PHOTO: 8
	
};
